apiVersion: v1
kind: Service
metadata:
  name: evolve-technologies-web-service
spec:
  selector:
    app: evolve-technologies-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
